config/routes.rb
Rails.application.routes.draw do

	root "tasks#index"
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  # def index - no longer needed with the :all_task filter
  #   @tasks = Task.all
  # end

  # GET /tasks/1
  # GET /tasks/1.json
  # def show - no longer needed with :set_tasks filter
  # end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.create(task_params)
    # @task = Task.new(task_params)

    # respond_to do |format|
    #   if @task.save
    #     format.html { redirect_to @task, notice: 'Task was successfully created.' }
    #     format.json { render :show, status: :created, location: @task }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @task.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
       @task.update(task_params)
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def all_tasks
      @tasks = Task.all
    end  

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spr18TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  	<div class="container">
	    <%= yield %>
	  </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, remote: true) do |form| %>

  <div class="form-group">
    <%= form.text_field :description, placeholder: "tasks description", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_field :deadline, id: :datetimepicker1, placeholder: "When is it due?", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Add Task", class: "btn btn-info" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="col-md-12">
	<div class="well">
		<li>
			<%= link_to task.description, task, remote: true, method: :delete, data: { confirm: "Are you sure?"} %>
			<%= task.deadline %>
			<%= link_to "Edit", edit_task_path(task), remote: true %>
		</li>
	</div>		
</div>

app/views/tasks/create.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);

app/views/tasks/destroy.js.erb
$('#tasks').html("<%= j (render @tasks) %>");

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col-md-3">
      <%= link_to new_task_path, remote: true do %>
          <button class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Add Task </button>
      <% end %>

      <div id="task-form" style="display:none;"></div> 
  </div>

  <div class="col-md-8"> 
    <h2>Heather's Tasks</h2>
    <div id="tasks">
      <div class="row">
        <%= render @tasks %>
      </div>
    </div>
  </div>

</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);